name: 'better'
description: 'An AI powered code review tool'
inputs:
  repo-token:  # id of input
    description: 'The repo token: { secrets.GITHUB_TOKEN }'
    required: true
  ai-model-api-key:
    description: 'The models api key: { secrets.<YOUR_AI_MODEL_API_KEY> }'
    required: true
  rules:
    description: 'The rules to consider for code review'
outputs:
  code-review-details:
    description: 'Code review details'
  review-id:
    description: 'Review id'
runs:
  using: 'node20'
  main: 'dist/index.js'
